<template>
  <iframe
    src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fremotejobsbr%2F&width=140&layout=button_count&action=like&size=large&show_faces=false&share=true&height=46&appId"
    width="140"
    height="46"
    style="border:none;overflow:hidden"
    scrolling="no"
    frameborder="0"
    allowTransparency="true"
    allow="encrypted-media"
  />
</template>
